# Generated by Django 5.2.10 on 2026-01-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TouristPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('history', models.TextField(help_text='Cultural and historical background of the place.')),
                ('image_main', models.ImageField(upload_to='places/main/')),
                ('timings', models.CharField(help_text='Example: 9:00 AM - 6:00 PM', max_length=100)),
                ('entry_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_name', models.CharField(help_text='District or nearby town', max_length=255)),
                ('how_to_reach', models.TextField(help_text='Details on travel via bus, taxi, or trekking.')),
                ('best_time_to_visit', models.CharField(max_length=200)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on landing page')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='tourism.category')),
            ],
        ),
    ]
