# Generated by Django 5.2.10 on 2026-01-13 10:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristplace',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='touristplace',
            name='longitude',
        ),
        migrations.AddField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default='fa-om', help_text='FontAwesome class for the icon', max_length=50),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
