# Generated by Django 5.2.10 on 2026-01-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon_class',
            field=models.CharField(default='fa-om', max_length=50),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='history',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='how_to_reach',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='location_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='timings',
            field=models.CharField(max_length=100),
        ),
    ]
