# Generated by Django 5.2.10 on 2026-01-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='description',
            field=models.TextField(default='Itinerary details coming soon...'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name',
            field=models.CharField(default='Sikkim Trip', max_length=200),
            preserve_default=False,
        ),
    ]
