# Generated by Django 5.2.10 on 2026-01-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_itinerary_description_itinerary_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
