# Generated by Django 5.2.10 on 2026-02-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0003_alter_itinerary_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='category_preference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='preferred_weather',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='travelers',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
